// Generated by https://quicktype.io

export interface Product {
  id: number;
  name: string;
  price: number;
  stock: number;
  image: string;
  description: string;
  category: Category;
}

export interface Category {
  id: number;
  name: string;
}
